# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'bento/centos-7.3'
  config.ssh.forward_agent = true
  #config.vm.synced_folder '.', '/home/vagrant/synced'

  #config.vm.provider :virtualbox do |vb|
  #  vb.customize ['modifyvm', :id, '--memory', '2048']
  #end

  config.vm.define :server do |host|
    host.vm.hostname = 'server'
    host.vm.network :private_network, ip: '192.168.101.10'
    #host.vm.network :private_network, ip: '192.168.100.10', :netmask => '255.255.255.0', virtualbox__intnet: '01'
    host.vm.provision :shell, path: 'server.sh'
    #host.vm.provision :shell, path: 'provision.sh', privileged: false

    #config.vm.provider :virtualbox do |vb|
    #  # enable promiscuous mode on the public network
    #  vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    #end
  end

  config.vm.define :client do |host|
    host.vm.hostname = 'client'
    host.vm.network :private_network, ip: '192.168.102.10'
    #host.vm.network :private_network, ip: '192.168.100.20', :netmask => '255.255.255.0', virtualbox__intnet: '01'
    host.vm.provision :shell, path: 'client.sh'
    #host.vm.provision :shell, path: 'provision.sh', privileged: false
  end
end
